import cv2
import numpy as np
from matplotlib import pyplot as plt 
from PIL import Image
img = cv2.imread('mark2.jpg')
#Пункт а
blur1 = cv2.GaussianBlur(img,(9,9),1)
blur2 = cv2.GaussianBlur(img,(9,9),4)	
blur3 = cv2.GaussianBlur(img,(9,9),6)
plt.subplot(121),plt.imshow(img),plt.title('Исходное изображение')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.subplot(122),plt.imshow(blur1),plt.title('сглаживание окном \nокном 9 на 9 1')
plt.xticks([]), plt.yticks ([])
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(blur1, cv2.COLOR_BGR2RGB))
plt.show()

plt.subplot(121),plt.imshow(img),plt.title('Исходное изображение')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.subplot(122),plt.imshow(blur2),plt.title('сглаживание окном \nокном 9 на 9 4')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(blur2, cv2.COLOR_BGR2RGB))
plt.show()

plt.subplot(121),plt.imshow(img),plt.title('Исходное изображение')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.subplot(122),plt.imshow(blur3),plt.title('сглаживание окном \nокном 9 на 9 6')
plt.xticks([]), plt.yticks([])
plt.show()
#пункт б
blur1 = cv2.GaussianBlur(img,(0,0),1)
blur2 = cv2.GaussianBlur(img,(0,0),4)
blur3 = cv2.GaussianBlur(img,(0,0),6)
plt.subplot(121),plt.imshow(img),plt.title('Исходное изображение')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.subplot(122),plt.imshow(blur1),plt.title('сглаживание окном \nокном 0 на 0 1')
plt.xticks([]), plt.yticks([])
plt.show()

plt.subplot(121),plt.imshow(img),plt.title('Исходное изображение')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.subplot(122),plt.imshow(blur2),plt.title('сглаживание окном \nокном 0 на 0 4')
plt.xticks([]), plt.yticks([])
plt.show()

plt.subplot(121),plt.imshow(img),plt.title('Исходное изображение')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.subplot(122),plt.imshow(blur3),plt.title('сглаживание окном \nокном 0 на 0 6')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(blur1, cv2.COLOR_BGR2RGB))
plt.show()
#пункт с 
blur1 = cv2.GaussianBlur(img,(0,0),1,9)
plt.subplot(121),plt.imshow(img),plt.title('Исходное изображение')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.subplot(122),plt.imshow(blur1),plt.title('пункт с ')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(blur1, cv2.COLOR_BGR2RGB))
plt.show()
#пункт d
blur1 = cv2.GaussianBlur(img,(0,0),9,1)
plt.subplot(121),plt.imshow(img),plt.title('Исходное изображение')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.subplot(122),plt.imshow(blur1),plt.title('Размытое изображение')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(blur1, cv2.COLOR_BGR2RGB))
plt.show()
#пункт е
blur1 = cv2.GaussianBlur(img,(0,0),1,9)
blur2 = cv2.GaussianBlur(blur1,(0,0),9,1)
plt.subplot(121),plt.imshow(img),plt.title('Исходное изображение')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.subplot(122),plt.imshow(blur2),plt.title('пункт e ')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(blur2, cv2.COLOR_BGR2RGB))
plt.show()
#пункт f
blur1 = cv2.GaussianBlur(img,(9,9),0)
plt.subplot(121),plt.imshow(blur2),plt.title('Пункт е ')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(blur2, cv2.COLOR_BGR2RGB))
plt.subplot(122),plt.imshow(blur1),plt.title('пункт f ')
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(blur1, cv2.COLOR_BGR2RGB))
plt.show()
